### ISSUE TITLE
Upstreaming group tests

### ISSUE THREAD

**Issue by annevk** [mensbeam/mime#1]
FWIW, I'd support hosting https://github.com/mensbeam/mime/blob/master/tests/cases/mime-groups.json somewhere on WPT. Perhaps there's some way we can eventually make use of it in browsers.

If you want to do this you should note in the README why there is no browser framework for them.

One thought I had looking at this file is that it might be nicer to have a groups property that takes an array of groups rather have a boolean property per group.

**Comment by JKingweb** [comment]
Great. I'll prepare a patch, as well as change the format as you suggest. The current one was easier to work with while I was building out the tests, but I recognize it's not very extensible at the very least.
